services:
  tap-api:
    build:
      context: ./tap-api/
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./tap-api/src/:/app/src
      - /app/node_modules
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
